version: 2

project_name: vibescript

builds:
  - id: vibes
    main: ./cmd/vibes
    binary: vibes
    env:
      - CGO_ENABLED=0

archives:
  - id: vibes
    builds:
      - vibes

checksum:
  disable: true

release:
  github:
    owner: mgomes
    name: vibescript
  prerelease: auto

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^Merge pull request'
